In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Superstore.csv", encoding='cp437')
print(df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

Analyzing the columns and datatypes in the dataset

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [5]:
df.columns=df.columns.str.replace(' ','_')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         9994 non-null   int64
 1   Order_ID       9994 non-null   str
 2   Order_Date     9994 non-null   str
 3   Ship_Date      9994 non-null   str
 4   Ship_Mode      9994 non-null   str
 5   Customer_ID    9994 non-null   str
 6   Customer_Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal_Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product_ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product_Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

Change data type

In [7]:
print(df.dtypes)

Row_ID             int64
Order_ID             str
Order_Date           str
Ship_Date            str
Ship_Mode            str
Customer_ID          str
Customer_Name        str
Segment              str
Country              str
City                 str
State                str
Postal_Code        int64
Region               str
Product_ID           str
Category             str
Sub-Category         str
Product_Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [ ]:
#change dtype to date time
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Ship_Date'] = pd.to_datetime(df['Ship_Date'])

In [9]:
print(df.dtypes)

Row_ID                    int64
Order_ID                    str
Order_Date       datetime64[us]
Ship_Date        datetime64[us]
Ship_Mode                   str
Customer_ID                 str
Customer_Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal_Code               int64
Region                      str
Product_ID                  str
Category                    str
Sub-Category                str
Product_Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

Convert sales and profit to apprx 2 decimals

In [10]:
df['Sales']

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9989     25.2480
9990     91.9600
9991    258.5760
9992     29.6000
9993    243.1600
Name: Sales, Length: 9994, dtype: float64

In [11]:
df[['Sales', 'Profit']] = df[['Sales', 'Profit']].round(2)

In [12]:
df[['Sales', 'Profit']]

       Sales  Profit
0     261.96   41.91
1     731.94  219.58
2      14.62    6.87
3     957.58 -383.03
4      22.37    2.52
...      ...     ...
9989   25.25    4.10
9990   91.96   15.63
9991  258.58   19.39
9992   29.60   13.32
9993  243.16   72.95

[9994 rows x 2 columns]

values inside a particular column from space to underscore

In [14]:
df['Ship_Mode']

0         Second Class
1         Second Class
2         Second Class
3       Standard Class
4       Standard Class
             ...
9989      Second Class
9990    Standard Class
9991    Standard Class
9992    Standard Class
9993      Second Class
Name: Ship_Mode, Length: 9994, dtype: str

In [15]:
df['Ship_Mode'] = df['Ship_Mode'].str.replace(' ', '_')

In [16]:
df['Ship_Mode']

0         Second_Class
1         Second_Class
2         Second_Class
3       Standard_Class
4       Standard_Class
             ...
9989      Second_Class
9990    Standard_Class
9991    Standard_Class
9992    Standard_Class
9993      Second_Class
Name: Ship_Mode, Length: 9994, dtype: str

Values inside customer name, split it to first name and last name

In [20]:
df[['First_Name', 'Last_Name']] = df['Customer_Name'].str.split(' ', n=1, expand=True)

In [21]:
df[['Customer_Name','First_Name', 'Last_Name']]

         Customer_Name First_Name     Last_Name
0          Claire Gute     Claire          Gute
1          Claire Gute     Claire          Gute
2      Darrin Van Huff     Darrin      Van Huff
3       Sean O'Donnell       Sean     O'Donnell
4       Sean O'Donnell       Sean     O'Donnell
...                ...        ...           ...
9989  Tom Boeckenhauer        Tom  Boeckenhauer
9990       Dave Brooks       Dave        Brooks
9991       Dave Brooks       Dave        Brooks
9992       Dave Brooks       Dave        Brooks
9993      Chris Cortes      Chris        Cortes

[9994 rows x 3 columns]

Remove columns

In [23]:
df.drop(['First Name', 'Last Name'], axis=1, inplace=True)

In [26]:
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,First_Name,Last_Name
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second_Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,Claire,Gute
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second_Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,Claire,Gute
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second_Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,Darrin,Van Huff
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard_Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03,Sean,O'Donnell
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard_Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,Sean,O'Donnell

display the names of all Ship Modes:

In [27]:
df['Ship_Mode'].unique()

<ArrowStringArray>
['Second_Class', 'Standard_Class', 'First_Class', 'Same_Day']
Length: 4, dtype: str

Find the most preferred Ship Mode by sales

In [29]:
df.groupby('Ship_Mode')['Sales'].sum().sort_values(ascending=False)

Ship_Mode
Standard_Class    1358215.84
Second_Class       459193.40
First_Class        351428.32
Same_Day           128363.09
Name: Sales, dtype: float64

Delete coulmn customer name

In [30]:
df.drop('Customer_Name',axis=1, inplace=True)

In [31]:
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Segment,Country,City,State,...,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,First_Name,Last_Name
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second_Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,Claire,Gute
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second_Class,CG-12520,Consumer,United States,Henderson,Kentucky,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,Claire,Gute
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second_Class,DV-13045,Corporate,United States,Los Angeles,California,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,Darrin,Van Huff
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard_Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03,Sean,O'Donnell
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard_Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,Sean,O'Donnell

Top 3 city with highest sales

In [33]:
df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(3)

City
New York City    256368.12
Los Angeles      175851.30
Seattle          119540.74
Name: Sales, dtype: float64

in City which category have more sale

In [34]:
df.groupby(['City', 'Category'])['Sales'].sum()

City      Category
Aberdeen  Office Supplies      25.50
Abilene   Office Supplies       1.39
Akron     Furniture           433.59
          Office Supplies    1113.39
          Technology         1183.01
                              ...
York      Furniture           422.06
          Office Supplies     395.92
Yucaipa   Office Supplies      50.80
Yuma      Office Supplies      55.36
          Technology          785.51
Name: Sales, Length: 1198, dtype: float64