In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("Superstore.csv", encoding='cp437')
print(df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB
None

In [ ]:
print(df['Segment'].unique())

['Consumer' 'Corporate' 'Home Office']

In [ ]:
print(df[df['Segment']=='Consumer'])

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2016-152156   11/8/2016  11/11/2016    Second Class
1          2  CA-2016-152156   11/8/2016  11/11/2016    Second Class
3          4  US-2015-108966  10/11/2015  10/18/2015  Standard Class
4          5  US-2015-108966  10/11/2015  10/18/2015  Standard Class
5          6  CA-2014-115812    6/9/2014   6/14/2014  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2014-110422   1/21/2014   1/23/2014    Second Class
9990    9991  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9991    9992  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9992    9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9993    9994  CA-2017-119914    5/4/2017    5/9/2017    Second Class

     Customer ID     Customer Name   Segment        Country             City  \
0       CG-12520       Claire Gute  Consumer  United States        Henderson
1       CG-12520       Claire Gute  Consumer  United States        Henderson
3       SO-20335    Sean O'Donnell  Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell  Consumer  United States  Fort Lauderdale
5       BH-11710   Brosina Hoffman  Consumer  United States      Los Angeles
...          ...               ...       ...            ...              ...
9989    TB-21400  Tom Boeckenhauer  Consumer  United States            Miami
9990    DB-13060       Dave Brooks  Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks  Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks  Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes  Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
5     ...       90032    West  FUR-FU-10001487        Furniture  Furnishings
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
5     Eldon Expressions Wood and Plastic Desk Access...   48.8600         7
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
3         0.45 -383.0310
4         0.20    2.5164
5         0.00   14.1694
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[5191 rows x 21 columns]

In [ ]:
df.groupby('Segment')['Sales'].sum()

Segment
Consumer       1.161401e+06
Corporate      7.061464e+05
Home Office    4.296531e+05
Name: Sales, dtype: float64

In [ ]:
df.loc[(df['Segment'] == 'Consumer') & (df['Region'] == 'South'),['Customer Name']].head()

     Customer Name
0      Claire Gute
1      Claire Gute
3   Sean O'Donnell
4   Sean O'Donnell
12    Andrew Allen

In [ ]:
df[df['Region']=='South']['Sales'].sum()

np.float64(391721.905)

In [ ]:
df.groupby('Region')['Sales'].sum()

Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

In [ ]:
df.groupby('Region')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)

    Region        Sales
3     West  725457.8245
1     East  678781.2400
0  Central  501239.8908
2    South  391721.9050

In [ ]:
#customers with max sales
df.groupby('Customer Name')['Sales'].sum().reset_index().sort_values(by='Sales',ascending=False).head()

     Customer Name      Sales
686    Sean Miller  25043.050
730   Tamara Chand  19052.218
622   Raymond Buch  15117.339
757   Tom Ashbrook  14595.620
6    Adrian Barton  14473.571

In [ ]:
df[(df['Region']=='South') & (df['Sales'] <= 10)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
108,109,CA-2017-119004,11/23/2017,11/28/2017,Standard Class,JM-15250,Janet Martin,Consumer,United States,Charlotte,...,28205,South,OFF-AR-10000390,Office Supplies,Art,Newell Chalk Holder,3.304,1,0.2,1.0738
233,234,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,OFF-BI-10001679,Office Supplies,Binders,GBC Instant Index System for Binding Systems,5.328,2,0.7,-3.5520
308,309,CA-2017-126774,4/15/2017,4/17/2017,First Class,SH-20395,Shahid Hopkins,Consumer,United States,Arlington,...,22204,South,OFF-AR-10002804,Office Supplies,Art,Faber Castell Col-Erase Pencils,4.890,1,0.0,2.0049
402,403,CA-2014-113166,12/24/2014,12/26/2014,First Class,LF-17185,Luke Foster,Consumer,United States,Miami,...,33180,South,OFF-PA-10001947,Office Supplies,Paper,Xerox 1974,9.568,2,0.2,3.4684
418,419,CA-2017-154816,11/6/2017,11/10/2017,Standard Class,VB-21745,Victoria Brennan,Corporate,United States,Richmond,...,40475,South,OFF-PA-10003845,Office Supplies,Paper,Xerox 1987,5.780,1,0.0,2.8322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9567,9568,CA-2014-130428,3/31/2014,3/31/2014,Same Day,TG-21640,Trudy Glocke,Consumer,United States,Tampa,...,33614,South,OFF-AR-10004027,Office Supplies,Art,Binney & Smith inkTank Erasable Desk Highlight...,4.032,2,0.2,1.0584
9753,9754,CA-2017-113705,3/27/2017,3/29/2017,Second Class,LC-16870,Lena Cacioppo,Consumer,United States,Richmond,...,23223,South,OFF-LA-10000476,Office Supplies,Labels,Avery 05222 Permanent Self-Adhesive File Folde...,8.260,2,0.0,3.7996
9760,9761,CA-2017-159135,11/4/2017,11/8/2017,Standard Class,KM-16375,Katherine Murray,Home Office,United States,Springdale,...,72762,South,OFF-AR-10000657,Office Supplies,Art,"Binney & Smith inkTank Desk Highlighter, Chise...",4.300,2,0.0,1.4190
9818,9819,CA-2015-162201,6/8/2015,6/12/2015,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Saint Petersburg,...,33710,South,OFF-AR-10003856,Office Supplies,Art,Newell 344,4.448,2,0.2,0.3336
9819,9820,CA-2015-162201,6/8/2015,6/12/2015,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Saint Petersburg,...,33710,South,OFF-LA-10001982,Office Supplies,Labels,Smead Alpha-Z Color-Coded Name Labels First Le...,9.000,3,0.2,3.1500

In [ ]:
#Count unique values
df['City'].nunique()

531

In [ ]:
#2. Display all unique values
df['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)