In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('https://github.com/datagy/mediumdata/raw/master/sample_pivot.xlsx', parse_dates=['Date'] )

In [3]:
df.head()

        Date Region                 Type  Units  Sales
0 2020-07-11   East  Children's Clothing   18.0    306
1 2020-09-23  North  Children's Clothing   14.0    448
2 2020-04-02  South     Women's Clothing   17.0    425
3 2020-02-28   East  Children's Clothing   26.0    832
4 2020-03-19   West     Women's Clothing    3.0     33

Aggregating Only Certain Colums in a Pandas Pivot Table

In [4]:
pivot=pd.pivot_table(data=df, index='Region', values='Sales')
pivot

             Sales
Region
East    408.182482
North   438.924051
South   432.956204
West    452.029412

In [5]:
pivot=pd.pivot_table(data=df, index='Region', values=['Sales','Units'])
pivot

             Sales      Units
Region
East    408.182482  19.732360
North   438.924051  19.202643
South   432.956204  20.423358
West    452.029412  19.294118

Working with Aggregation Methods in a Pandas PivotTable

In [6]:
#by default aggfunction is mean
pivot=pd.pivot_table(data=df, index='Region', values='Sales', aggfunc='sum')
pivot

         Sales
Region
East    167763
North   138700
South    59315
West     61476

Multiple Aggregation Method in a Pandas DataFrame

In [7]:
pivot=pd.pivot_table(data=df, index='Region', values='Sales', aggfunc=['sum','mean'])
pivot

           sum        mean
         Sales       Sales
Region
East    167763  408.182482
North   138700  438.924051
South    59315  432.956204
West     61476  452.029412

Specifying Different Aggregations Per Column

In [8]:
pivot=pd.pivot_table(data=df, index='Region', aggfunc={'Sales':'mean', 'Units':'sum'})
pivot

             Sales   Units
Region
East    408.182482  8110.0
North   438.924051  4359.0
South   432.956204  2798.0
West    452.029412  2624.0

Custom Aggregations in Pandas Pivot Tables

In [9]:
import numpy as np

In [10]:
# Defining a custo Onction
def mean_no_outliers(values):
    no_outliers= values.quantile([0.1,0.9])
    mean=np.mean(no_outliers)
    return mean
pivot=pd.pivot_table(data=df, index='Region', values='Sales', aggfunc=['mean', mean_no_outliers])
pivot

              mean mean_no_outliers
             Sales            Sales
Region
East    408.182482            436.0
North   438.924051            484.5
South   432.956204            434.1
West    452.029412            497.0

Add Columns to a Pandas Pivot Table

In [11]:
pivot=pd.pivot_table(data=df, index='Region', columns='Type', values='Sales')
pivot

Type    Children's Clothing  Men's Clothing  Women's Clothing
Region
East             405.743363      423.647541        399.028409
North            438.894118      449.157303        432.528169
South            412.666667      475.435897        418.924528
West             480.523810      465.292683        419.188679

Filter data by quarters (4 quarters in a month)

In [12]:
pivot=pd.pivot_table(data=df, index=['Region', df['Date'].dt.quarter], columns='Type', values='Sales')
pivot

Type         Children's Clothing  Men's Clothing  Women's Clothing
Region Date
East   1              423.241379      369.250000        428.948718
       2              274.800000      445.425000        456.816327
       3              425.382353      506.421053        342.386364
       4              453.866667      405.666667        364.795455
North  1              394.727273      450.869565        489.944444
       2              461.791667      478.916667        406.263158
       3              443.806452      482.947368        432.850000
       4              427.526316      388.478261        393.892857
South  1              509.400000      433.214286        465.785714
       2              376.363636      482.875000        463.687500
       3              430.909091      460.875000        370.937500
       4              353.538462      547.444444        332.571429
West   1              484.266667      532.307692        401.333333
       2              523.444444      394.571429        308.090909
       3              316.857143      406.285714        542.083333
       4              544.454545      467.928571        417.055556

Accessing data in a multi-index Pandas DataFrame_

In [15]:
print(pivot.loc[('East',1),"Men's Clothing"])

369.25

Customizing Pandas Pivot Tables

In [16]:
pivot=pd.pivot_table(data=df, index='Region', columns='Type', values='Sales', margins=True)
pivot

Type    Children's Clothing  Men's Clothing  Women's Clothing         All
Region
East             405.743363      423.647541        399.028409  408.182482
North            438.894118      449.157303        432.528169  438.924051
South            412.666667      475.435897        418.924528  432.956204
West             480.523810      465.292683        419.188679  452.029412
All              427.743860      444.257732        415.254717  427.254000

 Renaming column as total in a Pandas pivot table

In [17]:
pivot=pd.pivot_table(data=df, index='Region', columns='Type', values='Sales', margins=True, margins_name='Total')
pivot

Type    Children's Clothing  Men's Clothing  Women's Clothing       Total
Region
East             405.743363      423.647541        399.028409  408.182482
North            438.894118      449.157303        432.528169  438.924051
South            412.666667      475.435897        418.924528  432.956204
West             480.523810      465.292683        419.188679  452.029412
Total            427.743860      444.257732        415.254717  427.254000

Dealing with Missing Datai a Pandas Pivot Table

Sorting Pandas Pivot Table Data

In [18]:
pivot=pd.pivot_table(data=df, index='Region', values='Sales', sort=True)
pivot

             Sales
Region
East    408.182482
North   438.924051
South   432.956204
West    452.029412

Filtering Python Pivot Tables

In [19]:
pivot=pd.pivot_table(data=df, index=['Region', df['Date'].dt.quarter], values='Sales')
print(pivot[pivot['Sales'] > pivot['Sales'].mean()])

                  Sales
Region Date
North  1     462.142857
       2     442.034884
       3     447.200000
South  1     465.263158
       2     440.628571
West   1     475.000000
       3     444.884615
       4     466.209302

Dealing with Missing Datai a Pandas Pivot Table

In [21]:
df.loc[(df['Region']=='East') & (df['Type']=="Children's Clothing"), 'Sales']=np.nan

In [22]:
pivot=pd.pivot_table(data=df, index='Region', columns='Type', values='Sales')
pivot

Type    Children's Clothing  Men's Clothing  Women's Clothing
Region
East                    NaN      423.647541        399.028409
North            438.894118      449.157303        432.528169
South            412.666667      475.435897        418.924528
West             480.523810      465.292683        419.188679

 Filling Missing Values in a Pandas Pivot Table

In [23]:
pivot=pd.pivot_table(data=df, index='Region', columns='Type', values='Sales', fill_value=0)
pivot

Type    Children's Clothing  Men's Clothing  Women's Clothing
Region
East               0.000000      423.647541        399.028409
North            438.894118      449.157303        432.528169
South            412.666667      475.435897        418.924528
West             480.523810      465.292683        419.188679